Edited main.f95, run

diff --git a/code/run b/code/run
--- a/code/run
+++ b/code/run
@@ -4,7 +4,7 @@ gfortran -ffree-form main.f95
 ls -l
 ./a.out
 # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
-echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'main.f90'."
+echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'main.f95'."
 
 # The previous version of this file was commented-out and follows below:
 #
@@ -14,17 +14,15 @@ echo "Sorry, we couldn't automatically determine the right command for this file
 # ls -l
 # ./a.out
 # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
-# echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'BEM_Krylov.f90'."
+# echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'main.f90'."
 # 
 # # The previous version of this file was commented-out and follows below:
 # #
 # # #!/usr/bin/env bash
 # # set -ex
-# # 
-# # gfortran -ffree-form BEM_Krylov.f90
+# # gfortran -ffree-form main.f95
 # # ls -l
 # # ./a.out
-# # 
 # # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
 # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'BEM_Krylov.f90'."
 # # 
@@ -38,20 +36,33 @@ echo "Sorry, we couldn't automatically determine the right command for this file
 # # # ./a.out
 # # # 
 # # # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
-# # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''BEM Krylov.f90''."
+# # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run 'BEM_Krylov.f90'."
 # # # 
 # # # # The previous version of this file was commented-out and follows below:
 # # # #
 # # # # #!/usr/bin/env bash
 # # # # set -ex
 # # # # 
-# # # # gfortran -ffree-form BEM Krylo.f90
+# # # # gfortran -ffree-form BEM_Krylov.f90
 # # # # ls -l
 # # # # ./a.out
 # # # # 
-# # # # 
 # # # # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
 # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''BEM Krylov.f90''."
+# # # # 
+# # # # # The previous version of this file was commented-out and follows below:
+# # # # #
+# # # # # #!/usr/bin/env bash
+# # # # # set -ex
+# # # # # 
+# # # # # gfortran -ffree-form BEM Krylo.f90
+# # # # # ls -l
+# # # # # ./a.out
+# # # # # 
+# # # # # 
+# # # # # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
+# # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''BEM Krylov.f90''."
+# # # # # 
 # # # # 
 # # # 
 # # 
